import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(scriptDir, "../..");
const sourcePath = resolve(repoRoot, "shared/default-system-prompt.txt");
const typescriptPath = resolve(repoRoot, "pc/src/generated/defaultSystemPrompt.ts");
const kotlinPath = resolve(repoRoot, "android/app/src/main/java/dev/androidagent/DefaultSystemPrompt.kt");

const prompt = (await readFile(sourcePath, "utf8")).replace(/\r\n/g, "\n").trim();

const typescript = `// Generated by pc/scripts/generateDefaultSystemPrompt.mjs. Do not edit.\n` +
  `export const GENERATED_DEFAULT_SYSTEM_PROMPT = ${JSON.stringify(prompt)};\n`;

const kotlinPrompt = prompt
  .replace(/\$/g, "${'$'}")
  .split("\n")
  .map((line) => line.length === 0 ? "" : `        ${line}`)
  .join("\n");
const kotlin = `// Generated by pc/scripts/generateDefaultSystemPrompt.mjs. Do not edit.\n` +
  `package dev.androidagent\n\n` +
  `object DefaultSystemPrompt {\n` +
  `    val text: String = \"\"\"\n${kotlinPrompt}\n    \"\"\".trimIndent()\n` +
  `}\n`;

if (process.argv.includes("--check")) {
  const mismatches = [];
  for (const [path, expected] of [[typescriptPath, typescript], [kotlinPath, kotlin]]) {
    const actual = await readFile(path, "utf8").catch(() => "");
    if (actual !== expected) mismatches.push(path);
  }
  if (mismatches.length > 0) {
    throw new Error(`Generated default prompt files are stale: ${mismatches.join(", ")}`);
  }
} else {
  await Promise.all([
    writeFile(typescriptPath, typescript),
    writeFile(kotlinPath, kotlin)
  ]);
}
